version: "3.8"

services:
  backend:
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      target: backend
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=unlim_soft_test_case
      - DATABASE_USER=tikhon
      - DATABASE_PASSWORD=123
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
    - 8000:8000
    networks:
      backend:


  postgres:
    restart: always
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=unlim_soft_test_case
      - POSTGRES_USER=tikhon
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      backend:


volumes:
  postgres_data:

networks:
  backend: